---
docker_group_users: []
upgrade: no

tls_access: yes
tls_expiration_days: 3650
tls_sans: ["DNS:localhost", "IP:127.0.0.1", "DNS:host.docker.internal"]
tls_renew_certs: no
tls_fetch_certs: yes
tls_fetched_cert_path: "./fetched/certs"

storage_quotas: yes
storage_device: "/dev/nvme1n1"
