---
docker_group_users: []
upgrade: no

tls_access: yes
tls_expiration_days: 3650
tls_sans: ["DNS:localhost", "IP:127.0.0.1", "DNS:host.docker.internal"]
tls_renew_certs: no
tls_fetch_certs: yes
tls_fetched_cert_path: "./fetched/certs"

storage_quotas: yes
storage_device: "/dev/nvme1n1"

network_ip_pools: ["172.17.0.0/12", "192.168.0.0/16"]
network_prefix_length: 29

userns_remap_enabled: yes

oci_interceptor_enabled: yes
oci_interceptor_version: "latest"
oci_interceptor_upgrade: no
oci_interceptor_flags: ["--oi-readonly-networking-mounts"]

logs_max_size: "10m"
logs_max_files: 3

custom_networks_outbound_access_blocked: no
custom_networks_allowed_ips: []
