---
- name: Reload systemd config
  systemd:
    daemon_reload: yes
  become: yes

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: yes

- name: Update GRUB
  ansible.builtin.command:
    cmd: update-grub
  become: yes

- name: Reboot
  ansible.builtin.reboot:
  become: yes
