---

- include_tasks: clean-upgrade.yml
  when: upgrade and clean_upgrade
  args:
    apply:
      become: yes

- include_tasks: install.yml
  args:
    apply:
      become: yes

- include_tasks: service.yml
  when: cmgrd_service_enabled
  args:
    apply:
      become: yes

- include_tasks: artifact-server-install.yml
  args:
    apply:
      become: yes

- include_tasks: artifact-server-service.yml
  when: artifact_server_service_enabled
  args:
    apply:
      become: yes

- ansible.builtin.meta: flush_handlers

- name: Ensure cmgrd service is active
  ansible.builtin.service:
    name: cmgrd
    state: started
  become: yes
  when: cmgrd_service_enabled
  register: cmgrd_service
  until: cmgrd_service.status.ActiveState == "active"

- name: Ensure cmgr-artifact-server service is active
  ansible.builtin.service:
    name: cmgr_artifact_server
    state: started
  become: yes
  when: artifact_server_service_enabled
  register: artifact_server_service
  until: artifact_server_service.status.ActiveState == "active"
