---
- { include: clean-upgrade.yml, become: yes, when: upgrade and clean_upgrade }
- { include: install.yml, become: yes }
- { include: service.yml, become: yes, when: cmgrd_service_enabled }
- { include: artifact-server-install.yml, become: yes }
- { include: artifact-server-service.yml, become: yes, when: artifact_server_service_enabled }
- ansible.builtin.meta: flush_handlers
- name: Ensure cmgrd service is active
  ansible.builtin.service:
    name: cmgrd
    state: started
  become: yes
  when: cmgrd_service_enabled
  register: cmgrd_service
  until: cmgrd_service.status.ActiveState == "active"
- name: Ensure cmgr-artifact-server service is active
  ansible.builtin.service:
    name: cmgr_artifact_server
    state: started
  become: yes
  when: artifact_server_service_enabled
  register: artifact_server_service
  until: artifact_server_service.status.ActiveState == "active"
