---
- { include: install.yml, become: yes }
- { include: service.yml, become: yes, when: cmgrd_service_enabled }
- { include: artifact-server-install.yml, become: yes, when: artifact_server_enabled }
- { include: artifact-server-service.yml, become: yes, when: artifact_server_enabled }
