---

# Configure cmgrd to run as a systemd service.

- name: Ensure cmgrd systemd unit exists
  ansible.builtin.template:
    src: "cmgrd.service.j2"
    dest: "{{ systemd_unit_dir }}/cmgrd.service"
    lstrip_blocks: yes
    force: yes
  register: cmgrd_unit_updated
  notify:
    - Reload systemd config

- name: Determine whether to restart the cmgrd service
  assert: { that: true, quiet: true }
  changed_when: true
  notify:
    - Restart cmgrd
  when: installation_required or cmgrd_unit_updated.changed
