---

- ansible.builtin.include_tasks: needrestart.yml  # TODO(drop-jammy): remove release gate once jammy is phased out
  when: ansible_distribution_release == 'noble'
  args:
    apply:
      become: yes

- ansible.builtin.include_tasks: upgrade.yml
  when: upgrade_packages not in ["no", false]
  args:
    apply:
      become: yes

- ansible.builtin.include_tasks: journald.yml
  args:
    apply:
      become: yes

- ansible.builtin.include_tasks: sysctls.yml
  args:
    apply:
      become: yes

- ansible.builtin.include_tasks: hostname.yml
  when: hostname | default(None) is not none
  args:
    apply:
      become: yes
