---

- name: Precompute ephemeral port range parts
  set_fact:
    ephemeral_range_start: "{{ ephemeral_port_range.split('-')[0].strip() }}"
    ephemeral_range_end: "{{ ephemeral_port_range.split('-')[1].strip() }}"
  when: ephemeral_port_range is defined and ephemeral_port_range is not none

- name: Set ephemeral port range
  ansible.posix.sysctl:
    name: net.ipv4.ip_local_port_range
    value: "{{ ephemeral_range_start }} {{ ephemeral_range_end }}"
  when: ephemeral_range_start is defined and ephemeral_range_end is defined
