---
- name: Reload systemd config
  systemd:
    daemon_reload: yes
  become: yes

- name: Restart cmgrd
  ansible.builtin.service:
    name: cmgrd
    state: restarted
  become: yes

- name: Restart cmgr artifact server
  ansible.builtin.service:
    name: cmgr_artifact_server
    state: restarted
  become: yes
