---
# Docker Engine configuration

# Workaround for conflicting 'hosts' value in daemon.json and Docker's default systemd unit
# (see https://github.com/moby/moby/issues/25471)

- name: Ensure docker.service drop-in directory exists
  ansible.builtin.file:
    path: "{{ systemd_docker_drop_in_dir }}"
    state: directory

- name: Ensure docker.service drop-in unit exists
  ansible.builtin.copy:
    src: "docker.service_override.conf"
    dest: "{{ systemd_docker_drop_in_dir }}/override.conf"
    force: yes
  notify:
    - Reload systemd config
    - Restart Docker

- name: Ensure daemon config file exists
  ansible.builtin.template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    lstrip_blocks: yes
    force: yes
  notify:
    - Restart Docker
