---

# Install Docker Compose (v2). Currently (as of Docker Engine 20.10), this is not included as
# part of the docker-ce-cli package and must be installed separately.

# Rather than implement complicated logic to determine the latest version and potentially
# upgrade it, we just assume that Compose V2 will soon hit GA and be included in the CLI.
# At that point this set of tasks can be removed.

# See https://docs.docker.com/compose/cli-command/#install-on-linux

- name: Ensure Docker CLI plugins directory exists
  ansible.builtin.file:
    path: "/usr/local/lib/docker/cli-plugins"
    state: directory

- name: Ensure Compose V2 CLI plugin is installed
  ansible.builtin.get_url:
    dest: "/usr/local/lib/docker/cli-plugins/docker-compose"
    url: "https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-linux-x86_64"
    mode: "0755"
