---

# Configures iptables rules to block outbound network connectivity for
# containers on custom bridge networks.

# Outbound access remains available on the default (docker0) bridge network, so
# temporary containers used during `docker build` and containers without a
# custom network are unaffected.

- name: Ensure iptables rules script exists
  ansible.builtin.template:
    src: "docker_iptables_rules.sh.j2"
    dest: "{{ iptables_script_path }}"
    lstrip_blocks: yes
    force: yes
    mode: "0755"
  notify:
    - Restart iptables rules service

- name: Ensure iptables rules service exists
  ansible.builtin.template:
    src: "docker_iptables_rules.service.j2"
    dest: "{{ iptables_service_path }}"
    lstrip_blocks: yes
    force: yes
  notify:
    - Reload systemd config
    - Restart iptables rules service

- name: Ensure systemd unit is enabled
  ansible.builtin.systemd:
    name: docker_iptables_rules.service
    daemon_reload: yes
    enabled: yes
