---
- { include: install.yml, become: yes }
- { include: install-compose.yml, become: yes }
- { include: group.yml, become: yes }
- { include: certs.yml, become: yes, when: tls_access }
- { include: storage.yml, become: yes, when: storage_quotas }
- { include: parent-cgroup.yml, become: yes }
- { include: oci-interceptor.yml, become: yes, when: oci_interceptor_enabled }
- { include: iptables.yml, become: yes, when: custom_networks_outbound_access_blocked }
- { include: sysctls.yml, become: yes }
- { include: config.yml, become: yes }
- ansible.builtin.meta: flush_handlers
- name: Ensure Docker service is active
  ansible.builtin.service:
    name: docker
    state: started
  become: yes
  register: docker_service
  until: docker_service.status.ActiveState == "active"
- name: Ensure iptables rules service is active
  ansible.builtin.service:
    name: docker_iptables_rules
    state: started
  become: yes
  when: custom_networks_outbound_access_blocked
