---

- include_tasks: install.yml
  args:
    apply:
      become: yes

- include_tasks: group.yml
  args:
    apply:
      become: yes

- include_tasks: certs.yml
  when: tls_access | bool
  args:
    apply:
      become: yes

- include_tasks: storage.yml
  when: storage_quotas | bool
  args:
    apply:
      become: yes

- include_tasks: parent-cgroup.yml
  args:
    apply:
      become: yes

- include_tasks: oci-interceptor.yml
  when: oci_interceptor_enabled | bool
  args:
    apply:
      become: yes

- include_tasks: iptables.yml
  when: custom_networks_outbound_access_blocked | bool
  args:
    apply:
      become: yes

- include_tasks: firewall.yml
  args:
    apply:
      become: yes

- include_tasks: sysctls.yml
  args:
    apply:
      become: yes

- include_tasks: config.yml
  args:
    apply:
      become: yes

- ansible.builtin.meta: flush_handlers

- name: Ensure Docker service is active
  ansible.builtin.service:
    name: docker
    state: started
  become: yes
  register: docker_service
  until: docker_service.status.ActiveState == "active"

- name: Ensure iptables rules service is active
  ansible.builtin.service:
    name: docker_iptables_rules
    state: started
  become: yes
  when: custom_networks_outbound_access_blocked | bool
