---
- { include: install.yml, become: yes }
- { include: install-compose.yml, become: yes }
- { include: group.yml, become: yes }
- { include: certs.yml, become: yes, when: tls_access }
- { include: storage.yml, become: yes, when: storage_quotas }
- { include: parent-cgroup.yml, become: yes }
- { include: oci-interceptor.yml, become: yes, when: oci_interceptor_enabled }
- { include: config.yml, become: yes }
