---

- include_tasks: install.yml
  args:
    apply:
      become: yes

- include_tasks: configure.yml
  args:
    apply:
      become: yes

- include_tasks: service.yml
  args:
    apply:
      become: yes

- ansible.builtin.meta: flush_handlers

- name: Ensure agent service is active
  ansible.builtin.service:
    name: cloudwatch_agent
    state: started
  become: yes
  register: agent_service
  until: agent_service.status.ActiveState == "active"
